linters:
    Indentation:
        enabled: false

    PropertySortOrder:
        enabled: false

    StringQuotes:
        enabled: false

    SelectorDepth:
        max_depth: 4

    NestingDepth:
        max_depth: 4

    SelectorFormat:
        enabled: false
        convention: hyphenated_BEM

    NameFormat:
        convention: ^[0-9a-z\-_]+$
