version: '2'
services:
 data:
  build: ./data
  volumes:
  - ./../../:/var/www/html
 app:
  image: nginx:stable-alpine
  ports:
  - "${HTTP_PORT}:80"
  volumes:
  - ./app/default.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
  - data
